readings/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('all_readings/', views.all_readings, name='all_readings'),
    path('one_card/', views.one_card, name='one_card'),
    path('three_cards/<int:reading_type>', views.three_cards, name='three_cards'),
    path('cards/', views.CardsListView.as_view(), name='all_cards'),
    path('cards/<int:card_id>', views.card, name='card'),
    path('cards/<slug:attribute>', views.filter_by, name='filter_cards'),
    path('profile/', views.profile, name='profile'),
    path('change_password', views.ChangePasswordView.as_view(), name='change_password'),
    path('register/', views.register, name='register'),
    path('my_readings/', views.ReadingsByUserListView.as_view(), name='my_readings'),
    path('delete/<uuid:reading_id>', views.delete_reading, name='delete_reading'),
    path('search/', views.search, name='search'),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

tarot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('readings/', include('readings.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='readings/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +  
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

readings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import uuid

class Card(models.Model):
    ARCANA_CHOICES = (
    ('minor', 'Mažieji arkanai'),
    ('major', 'Didieji arkanai')
    )

    SUITS_CHOICES = (
    ('none', ''),
    ('wands', 'Lazdos'),
    ('cups', 'Taurės'),
    ('swords', 'Kardai'),
    ('pentacles', 'Monetos')
    )

    id = models.IntegerField(primary_key=True, help_text='Kortos seka kaladėje')
    image = models.ImageField('Nuotrauka', null=True)
    name = models.CharField('Pavadinimas', max_length=100, help_text='Kortos pavadinimas')
    description = models.TextField('Aprašymas', max_length=5000, help_text='Išsamus simbolizmo ir reikšmės aprašymas')
    meaning = models.TextField('Reikšmė', max_length=1000, help_text='Trumpas pagrindinių kortos reikšmių apibūdinimas')
    r_meaning = models.TextField('Reikšmė - apversta', max_length=1000, help_text='Trumpas pagrindinių apverstos kortos reikšmių apibūdinimas')
    arcana = models.CharField(
        'Arkanai',
        max_length=5, 
        choices=ARCANA_CHOICES,
        help_text='Pasirinkite arkanus',
        null=True
    )
    suit = models.CharField(
        'Rūšis',
        max_length=9, 
        choices=SUITS_CHOICES,
        null=True,
        help_text="Pasirinkite rūšį",
    )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('card-detail', args=[str(self.id)])

    class Meta:
        ordering = ['id']
    

class CardInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    card = models.CharField('Korta', max_length=200, help_text='Specifinis kortos egzempliorius, gautas būrimo metu')
    position = models.CharField('Kortos pozicija', max_length=10, help_text='Pozicija, kuria korta iškrito būrimo metu')

    def __str__(self):
        return f'{self.card}{self.position}'
    
    def display_info(self):
        return f'{self.card.arcana} {self.card.suit}'
    

class Reading(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    type = models.CharField('Tipas', max_length=50, help_text='Informacija apie būrimą', null=True)
    cards = models.CharField('Kortos', max_length=500, help_text='Trumpa informacija apie kortas, ištrauktas būrimo metu')
    date = models.DateTimeField('Sukurta', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.cards


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def __str__(self):
        return f'{self.user.username} profile'

readings/forms.py
from typing import Any, Dict
from .models import Profile
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=150,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, 
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exclude(username=self.instance.username).exists():
            raise forms.ValidationError('Šis el. pašto adresas jau yra naudojamas')
        return email
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and User.objects.filter(username=username).exclude(username=self.instance.username).exists():
            raise forms.ValidationError('Šis vartotojo vardas jau yra naudojamas')
        return username

readings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import User
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.db.models import Q, F
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView

from .models import Reading, Card, CardInstance
from .forms import UserUpdateForm
import random


def index(request):
    return render(request, 'index.html')


@csrf_protect
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
            
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojas su vardu {username} jau užregistruotas')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.success(request, f'Vartotojas {username} sėkmingai užregistruotas')
                    return redirect('login')
            
        else:
            messages.error(request, 'Slaptažodžiai nesutampa')
            return redirect('register')
        
    return render(request, 'register.html')


class CardsListView(generic.ListView):
    model = Card
    template_name = 'all_cards.html'
    

def card(request, card_id):
    specific_card = get_object_or_404(Card, pk=card_id)
    return render(request, 'card.html', {'card': specific_card})


def filter_by(request, attribute):
    cards = Card.objects.all()
    if attribute == 'major':
        cards = cards.filter(arcana='major')
    if attribute == 'minor':
        cards = cards.filter(arcana='minor')
    if attribute == 'wands':
        cards = cards.filter(suit='wands')
    if attribute == 'cups':
        cards = cards.filter(suit='cups')
    if attribute == 'swords':
        cards = cards.filter(suit='swords')
    if attribute == 'pentacles':
        cards = cards.filter(suit='pentacles')

    context = {
        'cards': cards,
        'attribute': attribute
    }
    return render(request, 'filter_cards.html', context=context)


def all_readings(request):
    return render(request, 'all_readings.html')


def one_card(request):
    all_cards = Card.objects.all()

    choice = random.sample(list(all_cards.values_list('pk', flat=True)), 1)

    chosen_card = CardInstance.objects.create(
        card = Card.objects.get(pk=choice[0]),
        position = random.choice(['', ', apversta'])
    )

    if request.user.is_authenticated:
        Reading.objects.create(
            type = 'Viena korta',
            cards = f'{chosen_card.card.name}{chosen_card.position}',
            user = request.user
        )

    return render(request, 'one_card.html', {'card': chosen_card})


def three_cards(request, reading_type):
    all_cards = Card.objects.all()

    choices = random.sample(list(all_cards.values_list('pk', flat=True)), 3)

    chosen_cards = CardInstance.objects.bulk_create(
        [
        CardInstance(
        card = Card.objects.get(pk=choices[0]),
        position = random.choice(['', ', apversta'])        
        ),
        CardInstance(
        card = Card.objects.get(pk=choices[1]),
        position = random.choice(['', ', apversta'])        
        ),
        CardInstance(
        card = Card.objects.get(pk=choices[2]),
        position = random.choice(['', ', apversta'])        
        )
        ]
    )

    reading_cards = []
    for card in chosen_cards:
        reading_cards.append(f'{card.card.name}{card.position}')
    reading_cards_str = ' | '.join(reading_cards)

    if reading_type == 1:
        reading_type_str = 'Praeitis, Dabartis, Ateitis'
    if reading_type == 2:
        reading_type_str = 'Jūs, Jūsų Kelias, Jūsų Potencialas'
    if reading_type == 3:
        reading_type_str = 'Situacija, Veiksmas, Baigtis'

    if request.user.is_authenticated:
        Reading.objects.create(
            type = reading_type_str,
            cards = reading_cards_str,
            user = request.user
        )

    context = {
        'card1': chosen_cards[0],
        'card2': chosen_cards[1],
        'card3': chosen_cards[2],
        'reading_type': reading_type
    }
    return render(request, 'three_cards.html', context=context)


class ReadingsByUserListView(LoginRequiredMixin, generic.ListView):
    model = Reading
    template_name = 'my_readings.html'
    paginate_by = 11

    def get_queryset(self):
        return Reading.objects.filter(user=self.request.user).order_by(F('date').desc())
    

def delete_reading(request, reading_id):
    if request.method == 'POST':
        reading = Reading.objects.get(pk=reading_id)
        reading.delete()
        return redirect('my_readings')
    return render(request, 'delete_reading.html', {'reading_id': reading_id})


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Profilis sėkmingai atnaujintas')
            return redirect(to='profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
    return render(request, 'profile.html', {'user_form': user_form})


class ChangePasswordView(PasswordChangeView):
    template_name = 'change_password.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        print('form valid')
        form.save()
        messages.success(self.request, 'Slaptažodis sėkmingai pakeistas')
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        if 'old_password' in form.errors:
            messages.error(self.request, 'Dabartinis slaptažodis neteisingas')
        if 'new_password2' in form.errors:
            messages.error(self.request, 'Slaptažodžiai nesutampa')
        return super().form_invalid(form)
    

def search(request):
    query = request.GET.get('query')
    search_results = Card.objects.filter(Q(name__icontains=query))
    return render(request, 'search.html', {'cards': search_results, 'query': query})

readings/templates/all_cards.html
{% extends "base.html" %}

{% block content %}
<div class="container shadow-sm p-3 mb-5" id="filter-by">
    <h2>Rūšiuoti kortas pagal</h2>
    <div class="container" id="ul-container">
        <div id="filter-by-arcana">
            <h5>Arkanus:</h5><hr class="smol">
            <ul id="arcana">
                <li><a href="{% url 'filter_cards' 'major' %}">Didieji Arkanai</a></li>
                <li><a href="{% url 'filter_cards' 'minor' %}">Mažieji Arkanai</a></li>
            </ul>
        </div>
        <div id="filter-by-suit">
            <h5>Rūšis:</h5><hr class="smol ler">
            <ul id="suit">
                <li><a href="{% url 'filter_cards' 'wands' %}">Lazdos</a></li>
                <li><a href="{% url 'filter_cards' 'cups' %}">Taurės</a></li>
                <li><a href="{% url 'filter_cards' 'swords' %}">Kardai</a></li>
                <li><a href="{% url 'filter_cards' 'pentacles' %}">Monetos</a></li>
            </ul>
        </div>
    </div>
</div>
{% if card_list %}
<div class="container" id="all-cards-container">
    {% for card in card_list %}
    <div>
        <div class="card shadow-sm">
            {{ card.name }}
            <a href="{% url 'card' card.pk %}" class="text-center">
            <img style="width: 200px; height: 351px;"
            alt="{{ card.name }}"
            src="{{ card.image.url }}">
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

{% endblock %}

readings/templates/all_readings.html
{% extends "base.html" %}

{% block content %}
<div class="container" id="readings-container">
    <h2>Prieš pradėdami būrimą...</h2>
    <h6>...kelias minutes susitelkite į klausimą, kurį norite užduoti kortoms ar į problemą, apie kurią norite gauti daugiau informacijos</h6><br>

    <img style="width: 60px; height: 70px;"
    src="https://orig00.deviantart.net/838f/f/2018/288/9/3/crystal_ball_by_king_lulu_deer-dcpkbz4.gif"><br><br>

    <ul id="readings">
    <li class="nav-item"><a href="{% url 'one_card' %}">Vienos kortos būrimas</a></li>
    <li class="nav-item"><a href="{% url 'three_cards' 1 %}">Praeitis, Dabartis, Ateitis</a></li>
    <li class="nav-item"><a href="{% url 'three_cards' 2 %}">Jūs, Jūsų Kelias, Jūsų Potencialas</a></li>
    <li class="nav-item"><a href="{% url 'three_cards' 3 %}">Situacija, Veiksmas, Baigtis</a></li>
    </ul>
    <hr>
    <small>
    Vienos kortos taro būrimai yra puikus būdas mokytis taro, susipažinti su kortomis ar nauju taro kortų rinkiniu ir tobulinti savo intuityvų skaitymą. Tam galite pasirinkti reguliarų, netgi kasdienį, ryto / popietės / vakaro laiką, kad ištrauktumėte kortą.
    Vienos kortos būrimas taip pat veikia gerai, kai tiesiog jaučiatės praradę kryptį ar nerimaujate ir norite greitos konsultacijos. Jums nereikia nieko pernelyg sudėtingo ar sunkaus, tiesiog vieno pranešimo, ties kuriuo galėsite sutelkti dėmesį.
    Toks būrimas taip pat gali atsakyti į vienkartinį, paprastą klausimą. 
    Tačiau, jei norite sudėtingo sprendimo ar atsakymo ilgesniam laikotarpiui nei vienai dienai, vienos kortos traukimo gali nepakakti. Tikriausiai turite daugiau nei vieną klausimą, susijusį su jūsų tema, todėl jums reikia daugiau kortų. 
    Taro aukso taisyklė yra vienas klausimas = viena korta. 
    </small>
</div>


{% endblock %}

readings/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Taro projektas</title>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@500&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm shadow-lg p-3 mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img style="height: 40px; height: 40px;"
        src="https://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/b14cf8bbef6f5f5.png">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'all_readings' %}">Būrimai</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'all_cards' %}">Visos kortos</a>
          </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'my_readings' %}">Mano būrimai</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
              {{ user.get_username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Atsijungti</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login'%}?next=/">Prisijungti</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Registruotis</a>
          </li>
        {% endif %}
        </ul>
        <div class="d-flex ms-auto order-last">
          <form class="d-flex" id="search" action="{% url 'search' %}" method="get">
            <input type="search" id="form1" class="form-control me-2" placeholder="Paieška" aria-label="Search" name="query"/>
          </form>
        </div>
      </div>
    </div>
  </nav>
  <div class="main shadow-lg p-3 mb-5">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'success' %}success{% else %}info{% endif %}" role="alert">
            {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

readings/templates/card.html
{% extends "base.html" %}

{% block content %}
<div class="container specific-card-page">
<div class="link">
<a href="{% url 'all_cards' %}"><small> ⟵ Grįžti į kortų sąrašą</small></a>
</div>
<div class="container specific-card">
<h2>{{ card.name }}</h2>
{% if card.arcana == 'major' %}
<p class="bigger"><strong>Didžiųjų Arkanų korta</strong></p>
{% elif card.arcana == 'minor' %}
<p class="bigger"><strong>Mažųjų Arkanų korta</strong></p>
{% endif %}
<hr>
<img src="{{ card.image.url }}" style="width: 220px; height: 386;">
<br><br>
<div class="desc">
<p class="bigger">{{ card.description }}</p>
</div>
<p><strong>Reikšmė: </strong>{{ card.meaning }}</p>
<p><strong>Reikšmė - apversta korta: </strong>{{ card.r_meaning }}</p>
<p><strong></strong></p>
<p><strong></strong></p>
</div>

{% endblock %}

readings/templates/change_password.html
{% extends "base.html" %}
{% block content %}
{% if user_form.errors %}
{% endif %}
    <div class="container profile">
        <h2>Slaptažodžio keitimas</h2><br>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="old-password">Dabartinis slaptažodis</label>
                <input type="password" name="old_password" id="old-password" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="new-password">Naujas slaptažodis</label>
                <input type="password" name="new_password1" id="new-password" class="form-control" required>
                <small class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti sudarytas tik iš skaičių</small>
            </div>
            <div class="form-group">
                <label for="repeat-password">Pakartoti slaptažodį</label>
                <input type="password" name="new_password2" id="repeat-password" class="form-control" required>
            </div>
            <br>
            <div class="div-button">
                <button type="submit" class="btn btn-lg" id="update-password">Atnaujinti</button>
            </div>
        </form>
    </div>

{% endblock %}

readings/templates/delete_reading.html
{% extends "base.html" %}

{% block content %}

<h2>Ištrinti įrašą</h2>
<p>Ar tikrai norite ištrinti būrimo įrašą?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn" value="Taip, ištrinti">
    <a href="{% url 'my_readings' %}">Ne, grįžti atgal</a>
</form>

{% endblock %}

readings/templates/filter_cards.html
{% extends "base.html" %}

{% block content %}

<div class="container" id="filter-by-container">
    <h2 id="filter-by-header">Rūšiuoti kortas pagal:</h2>
    <div class="container" id="ul-container">
        <div id="filter-by-arcana">
            <h5>Arkanus</h5>
            <ul id="arcana">
                <li><a href="{% url 'filter_cards' 'major' %}">Didieji Arkanai</a></li>
                <li><a href="{% url 'filter_cards' 'minor' %}">Mažieji Arkanai</a></li>
            </ul>
        </div>
        <div id="filter-by-suit">
            <h5>Rūšis</h5>
            <ul id="suit">
                <li><a href="{% url 'filter_cards' 'wands' %}">Lazdos</a></li>
                <li><a href="{% url 'filter_cards' 'cups' %}">Taurės</a></li>
                <li><a href="{% url 'filter_cards' 'swords' %}">Kardai</a></li>
                <li><a href="{% url 'filter_cards' 'pentacles' %}">Monetos</a></li>
            </ul>
        </div>
    </div>
    <hr>
</div>
{% if attribute == 'major' %}
<h2>Didieji Arkanai</h2>
{% elif attribute == 'minor' %}
<h2>Mažieji Arkanai</h2>
{% elif attribute == 'cups' %}
<h2>Taurės</h2>
{% elif attribute == 'wands' %}
<h2>Lazdos</h2>
{% elif attribute == 'swords' %}
<h2>Kardai</h2>
{% elif attribute == 'pentacles' %}
<h2>Monetos</h2>
{% endif %}<br>
<div class="container" id="all-cards-container">
    {% for card in cards %}
    <div class="d-flex align-items-stretch">
        <div class="card shadow-sm">
            {{ card.name }}
            <a href="{% url 'card' card.pk %}" class="text-center">
            <img style="width: 200px; height: 351px;"
            alt="{{ card.name }}"
            src="{{ card.image.url }}">
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

readings/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container index">
    <h1 id="main-title">Taro projektas</h1>
    <hr>
    <p>
        <strong>Taro yra kortų rinkinys, susidedantis iš 78 kortų</strong>, kiekviena iš jų - su savo vaizdais, simbolika ir istorija. 22 Didžiųjų Arkanų kortos atspindi gyvenimo, karmos bei dvasinius pamokymus, o 56 Mažųjų Arkanų kortos rodo kasdienius gyvenimo išbandymus ir sunkumus. 
    </p>
    <img style="width: 200px; height: 100px;"
    src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cf2836cb-5893-4a6c-b156-5a89d94fc721/dcpq6di-c12001a0-6bc9-4116-9b46-4096714289d3.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2NmMjgzNmNiLTU4OTMtNGE2Yy1iMTU2LTVhODlkOTRmYzcyMVwvZGNwcTZkaS1jMTIwMDFhMC02YmM5LTQxMTYtOWI0Ni00MDk2NzE0Mjg5ZDMuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.i9KoCE9osqk_SqiCmPs-OWcggnVjFqgEnFKWwAp6f7s">
    <br><br>
    <p>
        Kiekvienas dvasinis pamokymas, su kuriuo susiduriame savo gyvenime, gali būti rastas tarp septyniasdešimt aštuonių Taro kortų. Tai - tarsi veidrodis, leidžiantis pasiekti savo pasąmonę, išmintį ir atsakymus, gyvenančius kiekviename iš mūsų.
    </p>
    <div class="container" id="button-container">
        <a class="btn btn-lg" href="{% url 'all_readings' %}" role="button">Pasirinkti būrimą</a>
        <a class="btn btn-lg" href="{% url 'all_cards' %}" role="button">Peržiūrėti taro kortas</a>
    </div>
</div>
{% endblock %}

readings/templates/my_readings.html
{% extends "base.html" %}

{% block content %}

<table class="table table-hover">
  <tr>
    <th>Būrimo data</td>
    <th>Būrimas</th>
    <th>Kortos</th>
    <th></th>
  </tr>
  <tbody>
    {% for reading in reading_list %}
    <tr>
      <td>{{ reading.date }}</td>
      <td>{{ reading.type }}</td>
      <td>{{ reading.cards }}</td>
      <td> <a href="{% url 'delete_reading' reading.pk %}">Ištrinti</a> </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; pirmas</a>
      <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
    {% endif %}
    <span class="current">
        {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
    {% endif %}
  </span>
</div>  

{% endblock %}

readings/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h2>Paieškos pagal "{{query}}" rezultatai:</h2>
  </br>
  <div class="results d-md-flex-row">
  {% if cards %}
    {% for card in cards %}
        <div class="result card shadow-sm">
            {{ card.name }}
            <a href="{% url 'card' card.pk %}" class="text-center">
            <img style="width: 200px; height: 351px;"
            alt="{{ card.name }}"
            src="{{ card.image.url }}">
            </a>
        </div>
    {% endfor %}
  </div>
  {% else %}
  <p>Pagal jūsų užklausą nieko neradome</p>
  {% endif %}


  {% endblock %}